POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "hubbabaloo",
  "author": "joe book",
  "url": "sfadsfdss",
  "likes": 3
}

###
# Unauthorized
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Unauthorized blog",
  "author": "bobby crank",
  "url": "fddsfsdf",
  "likes": 1
}

###
# Authorized
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dsaXN0dGVzdCIsImlkIjoiNjI5NzgxYjZmYjU5YjIwMWE3MDA5ODRhIiwiaWF0IjoxNjU0MTA1OTAwfQ.WVxjkeK-ighcwZCDHnQVctm4QJL1wU81COpbGadgNm4

{
  "title": "Authorized blog",
  "author": "Blob L. Test",
  "url": "fddsfsdf",
  "likes": 1
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Blog L. Test",
  "username": "hacker", 
  "password": "password123"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "bloglisttest",
  "password": "testtesttest"
}