POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "hubbabaloo",
  "author": "joe book",
  "url": "sfadsfdss",
  "likes": 3
}

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "One more blog",
  "author": "bobby crank",
  "url": "fddsfsdf",
  "likes": 1
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Blog L. Test",
  "username": "bloglisttest",
  "password": "testtesttest"
}